## sudo is required to install gcc-4.8
sudo: required

language: cpp

compiler:
  - clang
  - gcc

before_install:
    ## TODO: drop this once travis updates gcc to 4.8
    - if [ "$CXX" = "g++" ]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test; fi
    - if [ "$CXX" = "g++" ]; then sudo apt-get -qq update; fi
    - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.8; fi
    - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi

before_script:
  - cd src
  - cmake .

script: make

notifications:
  email: false

os:
  - linux
